### ISSUE TITLE
Confirmation this works for xiaomi watches?

### ISSUE THREAD

**Issue by FoxxMD** [Silleellie/dnd-bedtime-sync#8]
The readme mentions syncing for xaomi watches but its not clear how/why this works. Can you elaborate on which watches or works on (or which you expect it to work with?)

I'm looking at getting a Redmi Smart Watch 3 but being unable to sync DND with my pixel 6 would be a dealbreaker for me.

**Comment by Silleellie** [comment]
Hello, basically for Xiaomi watches there's the option to enable sleep mode upon DND changes, that's a workaround since those phones do not have the "Digital wellbeing" setting which is found in stock android.

Long story short, for Xiaomi phones:

- DND sync should work
- Bedtime mode works if the "Enable Bedtime mode on DND sync" is enabled in the phone app
